# Generated by Django 5.2.3 on 2025-06-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_productsmodel_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscategory',
            options={'ordering': ('category_id',), 'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
        migrations.RenameField(
            model_name='productscategory',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='productscategory',
            name='id',
        ),
        migrations.AddField(
            model_name='productscategory',
            name='category_descriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productscategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
